"""add task id to blocks

Revision ID: 2832b2199053
Revises: 368614ea4428
Create Date: 2026-02-03 15:23:55.807713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2832b2199053'
down_revision: Union[str, Sequence[str], None] = '368614ea4428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_blocks', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_schedule_blocks_task_id'), 'schedule_blocks', ['task_id'], unique=False)
    op.create_index('ix_schedule_blocks_user_task', 'schedule_blocks', ['user_id', 'task_id'], unique=False)
    op.create_foreign_key(None, 'schedule_blocks', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_blocks', type_='foreignkey')
    op.drop_index('ix_schedule_blocks_user_task', table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_task_id'), table_name='schedule_blocks')
    op.drop_column('schedule_blocks', 'task_id')
    # ### end Alembic commands ###
