"""add task preferences

Revision ID: 368614ea4428
Revises: 9c3b2e0b6f3a
Create Date: 2026-02-03 15:04:01.248480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368614ea4428'
down_revision: Union[str, Sequence[str], None] = '9c3b2e0b6f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_by_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('priority_tag', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('splittable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tasks', sa.Column('preferred_time', sa.String(length=20), server_default='any', nullable=False))
    op.add_column('tasks', sa.Column('focus_need', sa.String(length=20), server_default='medium', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'focus_need')
    op.drop_column('tasks', 'preferred_time')
    op.drop_column('tasks', 'splittable')
    op.drop_column('tasks', 'priority_tag')
    op.drop_column('tasks', 'estimated_by_ai')
    # ### end Alembic commands ###
