"""create schedule_blocks

Revision ID: f2ec7a44cec9
Revises: e714fa4cedfb
Create Date: 2026-01-30 00:07:50.588268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ec7a44cec9'
down_revision: Union[str, Sequence[str], None] = 'e714fa4cedfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blocks_user_id'), 'schedule_blocks', ['user_id'], unique=False)
    op.create_index('ix_schedule_blocks_user_start', 'schedule_blocks', ['user_id', 'start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_blocks_user_start', table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_user_id'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    # ### end Alembic commands ###
